from . import fleet_vehicle
from . import fleet_driver
from . import fleet_expense
from . import fleet_maintenance
from . import fleet_reservation
from . import fleet_document
from . import fleet_fuel_log
from . import fleet_insurance
from . import fleet_inspection
from . import fleet_odometer
from . import fleet_revenue
from . import fleet_schedule
from . import fleet_driver_document
from . import fleet_driver_performance
